[build]
  publish = "public"

[[redirects]]
  from = "/host"
  to = "/host.html"
  status = 200

[[redirects]]
  from = "/display"
  to = "/display.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
